---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sap-btp-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sap-btp-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{.Release.Namespace}}
