{{- $cn := printf "sap-btp-operator-webhook-service"  }}
{{- $ca := genCA (printf "%s-%s" $cn "ca") 3650 }}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
{{- if not .Values.manager.certificates }}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: {{.Release.Namespace}}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sap-btp-service-operator-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
---
{{- end}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  {{- if .Values.manager.certificates.certManager }}
  annotations:
    cert-manager.io/inject-ca-from: {{.Release.Namespace}}/sap-btp-operator-serving-cert
  {{- end}}
  name: sap-btp-operator-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: sap-btp-operator-webhook-service
        namespace: {{.Release.Namespace}}
        path: /mutate-services-cloud-sap-com-v1-servicebinding
      {{- if not .Values.manager.certificates }}
      caBundle: {{ b64enc $ca.Cert }}
      {{- end }}
      {{- if .Values.manager.certificates.selfSigned }}
      caBundle: {{.Values.manager.certificates.selfSigned.caBundle }}
      {{- end }}
      {{- if .Values.manager.certificates.gardenerCertManager }}
      caBundle: {{.Values.manager.certificates.gardenerCertManager.caBundle }}
      {{- end }}
    failurePolicy: Fail
    name: mservicebinding.kb.io
    rules:
      - apiGroups:
          - services.cloud.sap.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - servicebindings
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: sap-btp-operator-webhook-service
        namespace: {{.Release.Namespace}}
        path: /mutate-services-cloud-sap-com-v1-serviceinstance
      {{- if not .Values.manager.certificates }}
      caBundle: {{ b64enc $ca.Cert }}
      {{- end }}
      {{- if .Values.manager.certificates.selfSigned }}
      caBundle: {{.Values.manager.certificates.selfSigned.caBundle }}
      {{- end }}
      {{- if .Values.manager.certificates.gardenerCertManager }}
      caBundle: {{.Values.manager.certificates.gardenerCertManager.caBundle }}
      {{- end }}
    failurePolicy: Fail
    name: mserviceinstance.kb.io
    rules:
      - apiGroups:
          - services.cloud.sap.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - serviceinstances
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  {{- if .Values.manager.certificates.certManager }}
  annotations:
    cert-manager.io/inject-ca-from: {{.Release.Namespace}}/sap-btp-operator-serving-cert
  {{- end}}
  name: sap-btp-operator-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: sap-btp-operator-webhook-service
        namespace: {{.Release.Namespace}}
        path: /validate-services-cloud-sap-com-v1-servicebinding
      {{- if not .Values.manager.certificates }}
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWekNDQWorZ0F3SUJBZ0lVS1BtaFBlZjlXeGJiR1FyRnU5ZWpWcGFoL2prd0RRWUpLb1pJaHZjTkFRRUwKQlFBd096RTVNRGNHQTFVRUF3d3djMkZ3TFdKMGNDMXZjR1Z5WVhSdmNpMTNaV0pvYjI5ckxYTmxjblpwWTJVdQphM2x0WVMxemVYTjBaVzB1YzNaak1CNFhEVEl5TURFeE1qRTFNamN3T0ZvWERUTXlNREV4TURFMU1qY3dPRm93Ck96RTVNRGNHQTFVRUF3d3djMkZ3TFdKMGNDMXZjR1Z5WVhSdmNpMTNaV0pvYjI5ckxYTmxjblpwWTJVdWEzbHQKWVMxemVYTjBaVzB1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMDR4NQpLMkcxSU5RZFpyemxTSVJPdC9KVHBmc0tqRGg2aEY0ajBVdTJFSDJJTXc2TFp1dDBTaWwxZFlaZlU0YVAxZFMzClhYZzI3VkpQcm4va2pGQW93S2hDUUFnQllYRjNtK205OUFFbXhVaGdySVpTamR5Y3VpZFlqYytnVGFaeXlFSTIKbGJNUDRlcXBNZXVjSDN0RFJhQmZEUzhhc0sxYXFxWkdkajVZU0h3c3piTmRZUnpDQzRKUVFyQUl2b0lWd0ZXMgpkVXVtY0t6aXFNWVFPTmxOUDN1N1VuWkZCNGljZjF4aEdJZTNlVXBaWGlwMGp0VmtZc1M4RitselV2bThWcmlQCkxKbEhRWGpxUm1GeFA2RGFTWDJhbkl4cDBQdFNpazRjekVSMzJRSCtPbnVjZks5NW9Vd0JXOFpiU2RQMDNRek0KOGNLUXd5dURMS0xsOGh4dW1RSURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVXTlUwcjlSbVIzZ1RvUHlDbEJuawpwSlUzRmNvd0h3WURWUjBqQkJnd0ZvQVVXTlUwcjlSbVIzZ1RvUHlDbEJua3BKVTNGY293RHdZRFZSMFRBUUgvCkJBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXh0R0hrQ0plRHpmZ2pqT2dVRzF0ODJCVlYySzEKSkVBVFBNbEZEVmk4aCtmbWx6aGU2QkQ4WHpUVDdBb0VTQmloQk92MzB6UVd1a3NFT0NvbmV4V1hDOEcyQVQ5cAphS05BNG1WbDNUelgrTDRHVHNVOEhtcnAvYWE2MlVoRTBySDdvMGZJS2gxZk4wcHIyT0xKZldPYWpSeWRKQ1RuCjYxZW1xVjIwK0xReVdoNTVtYm9COUZRN3JlTjkzdHRNcm9LM3R1c0VSckJCREV0NFVHaWFtTFFuZm4wOS9jOFcKZEt5YXFqclVtVFhMWjNaVWdHUStGeFZSTWIwamRKa2dpZnFFQnBLUENWNzhYTzQrQW5LUm5qa2dIUTZqRmtJNgo3V1B3eDFZTmIvNThrbFM1clZYc3ZsWnQwTUpMYjllanFKRit3Qk9jbXhPS3dPbHdDZEs4VlRKZmhnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=" # selfsigned
      {{- end }}
      {{- if .Values.manager.certificates.selfSigned }}
      caBundle: {{.Values.manager.certificates.selfSigned.caBundle }}
      {{- end }}
      {{- if .Values.manager.certificates.gardenerCertManager }}
      caBundle: {{.Values.manager.certificates.gardenerCertManager.caBundle }}
      {{- end }}
    failurePolicy: Fail
    name: vservicebinding.kb.io
    rules:
      - apiGroups:
          - services.cloud.sap.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - servicebindings
    sideEffects: None