---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  {{- if .Values.manager.certificates.certManager }}
  annotations:
    cert-manager.io/inject-ca-from: {{.Release.Namespace}}/sap-btp-operator-serving-cert
  {{- end }}
  creationTimestamp: null
  name: sap-btp-operator-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: sap-btp-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-services-cloud-sap-com-v1alpha1-servicebinding
    {{- if not .Values.manager.certificates }}
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvRENDQW9pZ0F3SUJBZ0lVVXV5bkJNeWNoQzRheU1KQjFiMnNHYTV1R0NNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWdUQms5eVpXZHZiakVSTUE4R0ExVUVCeE1JVUc5eQpkR3hoYm1ReEV6QVJCZ05WQkFvVENrdDFZbVZ5Ym1WMFpYTXhDekFKQmdOVkJBc1RBa05CTVJNd0VRWURWUVFECkV3cExkV0psY201bGRHVnpNQjRYRFRJeE1EWXlOVEUyTURZd01Gb1hEVEkyTURZeU5ERTJNRFl3TUZvd2FERUwKTUFrR0ExVUVCaE1DVlZNeER6QU5CZ05WQkFnVEJrOXlaV2R2YmpFUk1BOEdBMVVFQnhNSVVHOXlkR3hoYm1ReApFekFSQmdOVkJBb1RDa3QxWW1WeWJtVjBaWE14Q3pBSkJnTlZCQXNUQWtOQk1STXdFUVlEVlFRREV3cExkV0psCmNtNWxkR1Z6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwUWQrUm1Gc0prMkIKeExBcS8zMnpOSmZHcXlzKzhJUWRIVWlGaG9YTXJKYlk4ck1zUjV2R0UwdXduc2Y3ZThlY2FUR1ZpY0lMVFJjOApyaUVYcFhiUitheFdQQTA0QTRuekFXbS9BdS9Ta3R6bElJNGVDdFgyaXhOVW9JSzRFbWlBWXNFVlZLZDBPOE4vCng2WVNHYjBlL2toakE0UldMUzR5ZmE0aFNzeGRTSTEvb2pwb2dlQ2xTOWxoTTNlR2ZTN2xrbmM1VFBGN2R6b0QKREZpdXVyTlY3VGFYWmJ0LzZ1bkhqRWYyQzR3Y0FCRnUxOHI4S0JXV0tvVmRBeElwZkhoWnhIKzR1MGlDdFJRVAp4TEt3d2lJc3pUaStYdWdsVTJpQkErdUpXTG9LRmtPTjFQMGRUWnUrUWpnblZpd0lwS2d1YUR3aUlnR2w5NXZkCmZFWGVaMzZQQ1FJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVWdvVGJKVTJxUWgzcXhGblVpNGVUU3hBMk5ic3dEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUR4cUIzMFhGNkJzNkN3UWpPZjk1Qnh2emR4ak4zNy9EZ0RxYks1MDRJa0hJTmNjSlp3aEpNcTVLUmlhCmE1RFpNVlVETE1YbHV1WnlNNjJGRkUrQXZ4d1h2bXYzS2ttZ29lQ0QwZ3RqTXYyWXQ1NGl3ci8zTmhPRGJmaUsKUHYyaWV5QndIMWlOWXlQRW9HNjBBRHJlV2ZJNyt0Z3hPN2dhZkJTZTdBeE9NbytSTGVVNDRRampKcWIwaG9rYwpZaW5FNGdHV2pTL2x3a3U5ZFdicXZ0REM1NTh1MU5UOTRHRGVBM0M1YmtNNVZVa05lNFZGUEQwSFhjdDdlbVlNCmFOd2RZSllkbCtGU0R2eUlKeG1xdjRYdEEyL2srUGRyRVBwdW5iL0FRYUVrTjJUMi9LVWhBSTJiYzdmREZmZWoKZ0IwVnpLNHNkYkczYkJCVzVWTEJRTlhud0FnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    {{- end }}
    {{- if .Values.manager.certificates.selfSigned }}
    caBundle: "{{.Values.manager.certificates.selfSigned.caBundle }}"
    {{- end }}
    {{- if .Values.manager.certificates.certManagement }}
    caBundle: {{.Values.manager.certificates.certManagement.caBundle }}
    {{- end }}
  failurePolicy: Fail
  name: mservicebinding.kb.io
  rules:
  - apiGroups:
    - services.cloud.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicebindings
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: sap-btp-operator-webhook-service
      namespace: {{.Release.Namespace}}
      path: /mutate-services-cloud-sap-com-v1alpha1-serviceinstance
    {{- if not .Values.manager.certificates }}
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvRENDQW9pZ0F3SUJBZ0lVVXV5bkJNeWNoQzRheU1KQjFiMnNHYTV1R0NNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWdUQms5eVpXZHZiakVSTUE4R0ExVUVCeE1JVUc5eQpkR3hoYm1ReEV6QVJCZ05WQkFvVENrdDFZbVZ5Ym1WMFpYTXhDekFKQmdOVkJBc1RBa05CTVJNd0VRWURWUVFECkV3cExkV0psY201bGRHVnpNQjRYRFRJeE1EWXlOVEUyTURZd01Gb1hEVEkyTURZeU5ERTJNRFl3TUZvd2FERUwKTUFrR0ExVUVCaE1DVlZNeER6QU5CZ05WQkFnVEJrOXlaV2R2YmpFUk1BOEdBMVVFQnhNSVVHOXlkR3hoYm1ReApFekFSQmdOVkJBb1RDa3QxWW1WeWJtVjBaWE14Q3pBSkJnTlZCQXNUQWtOQk1STXdFUVlEVlFRREV3cExkV0psCmNtNWxkR1Z6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwUWQrUm1Gc0prMkIKeExBcS8zMnpOSmZHcXlzKzhJUWRIVWlGaG9YTXJKYlk4ck1zUjV2R0UwdXduc2Y3ZThlY2FUR1ZpY0lMVFJjOApyaUVYcFhiUitheFdQQTA0QTRuekFXbS9BdS9Ta3R6bElJNGVDdFgyaXhOVW9JSzRFbWlBWXNFVlZLZDBPOE4vCng2WVNHYjBlL2toakE0UldMUzR5ZmE0aFNzeGRTSTEvb2pwb2dlQ2xTOWxoTTNlR2ZTN2xrbmM1VFBGN2R6b0QKREZpdXVyTlY3VGFYWmJ0LzZ1bkhqRWYyQzR3Y0FCRnUxOHI4S0JXV0tvVmRBeElwZkhoWnhIKzR1MGlDdFJRVAp4TEt3d2lJc3pUaStYdWdsVTJpQkErdUpXTG9LRmtPTjFQMGRUWnUrUWpnblZpd0lwS2d1YUR3aUlnR2w5NXZkCmZFWGVaMzZQQ1FJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVWdvVGJKVTJxUWgzcXhGblVpNGVUU3hBMk5ic3dEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUR4cUIzMFhGNkJzNkN3UWpPZjk1Qnh2emR4ak4zNy9EZ0RxYks1MDRJa0hJTmNjSlp3aEpNcTVLUmlhCmE1RFpNVlVETE1YbHV1WnlNNjJGRkUrQXZ4d1h2bXYzS2ttZ29lQ0QwZ3RqTXYyWXQ1NGl3ci8zTmhPRGJmaUsKUHYyaWV5QndIMWlOWXlQRW9HNjBBRHJlV2ZJNyt0Z3hPN2dhZkJTZTdBeE9NbytSTGVVNDRRampKcWIwaG9rYwpZaW5FNGdHV2pTL2x3a3U5ZFdicXZ0REM1NTh1MU5UOTRHRGVBM0M1YmtNNVZVa05lNFZGUEQwSFhjdDdlbVlNCmFOd2RZSllkbCtGU0R2eUlKeG1xdjRYdEEyL2srUGRyRVBwdW5iL0FRYUVrTjJUMi9LVWhBSTJiYzdmREZmZWoKZ0IwVnpLNHNkYkczYkJCVzVWTEJRTlhud0FnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    {{- end }}
    {{- if .Values.manager.certificates.selfSigned }}
    caBundle: "{{.Values.manager.certificates.selfSigned.caBundle }}"
    {{- end }}
    {{- if .Values.manager.certificates.certManagement }}
    caBundle: {{.Values.manager.certificates.certManagement.caBundle }}
    {{- end }}
  failurePolicy: Fail
  name: mserviceinstance.kb.io
  rules:
  - apiGroups:
    - services.cloud.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceinstances
  sideEffects: None
